### ISSUE TITLE
To Complete Viewpoint SPV02a Physical Structure

### ISSUE THREAD

**Issue by parkaneric** [GfSE/SAF-Specification#17]
Please add the viewpoint SPV02a Physical Structure profile to the VP specification.

Assumed priority: high

Acceptance Criteria:
- viewpoint page (https://github.com/GfSE/SAF-Specification/blob/main/developing-saf/viewpoints/Physical-Structure-Viewpoint.md) includes also the profile definition
- maturity is in state released

**Comment by haarer** [comment]
The concerns need to be reviewed. they are partially redundant. and lacking a rationale
![redundant-concerns](https://github.com/GfSE/SAF-Specification/assets/14995831/e0649aba-600b-408f-873f-aa91696e227f)

See https://github.com/GfSE/SAF-Specification/blob/main/concerns.md 
( search for "physical structure viewpoint" in browser

**Comment by parkaneric** [comment]
1. Is each Physical Element a real-world and existing part and is an additional stereotype or tagged value required to differentiate between real-world parts and "virtual" assembly groups?
2. There are multiple consumers of this structure (e.g. Security Specialist or Hardware Developer) who would compile their dedicated domain architecture. These domain specific architectures will not follow this defined structure but will define their own decomposition. How do we intend to handle this? Allow multiple decompositions is parallel in different contexts ... ?

**Comment by haarer** [comment]
Am 5. Oktober 2023 09:03:15 MESZ schrieb Eric Parkan ***@***.***>:
>1. Is each Physical Element a real-world and existing part and is an additional stereotype or tagged value required to differentiate between real-world parts and "virtual" assembly groups?
>2. There are multiple consumers of this structure (e.g. Security Specialist or Hardware Developer) who would compile their dedicated domain architecture. These domain specific architectures will not follow this defined structure but will define their own decomposition. How do we intend to handle this? Allow multiple decompositions is parallel in different contexts ... ? 
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/GfSE/SAF-Specification/issues/17#issuecomment-1748209694
>You are receiving this because you were assigned.
>
>Message ID: ***@***.***>
1. There are currently Stereotypes for Hardware, Software and General physical Elements (Consists of both).
Perhaps we should drop this Idea and just allow physical Elements to be assig ed To one or more disciplines?

Noone Likes the v-model xt anyway 😁

This assigment xould be done for ports as Well.

IT should Not be done by stereotypes, too static

2. Different consumers, yes.
But should they really make their own structures?
I'd rather say they should use Viewpoints for that purpose. Or even multiple ibds focusing on for Engineering domains
-- 
Gruß,
Alexander

**Comment by jantaeubrich** [comment]
Erics and my question is related to assembly groups that are made of physical pieces and may observe specific characteristics like being a spare part or having drawings that show how to assemble them. The question is, if we need to distinguish them like we potentially do with hardware and softare parts.

And we also discussed the potential for different structural breakdowns. I am quite sure that in our systems the structural breakdown in the BOM is slightly different than the structure of logistical breakdown. Currently they are handled in different tools, but if we bring them together in SAF we have to find a proper way to do it.

**Comment by haarer** [comment]
Am 6. Oktober 2023 07:51:42 MESZ schrieb "Jan Täubrich" ***@***.***>:
>Erics and my question is related to assembly groups that are made of physical pieces and may observe specific characteristics like being a spare part or having drawings that show how to assemble them. The question is, if we need to distinguish them like we potentially do with hardware and softare parts.
>
>And we also discussed the potential for different structural breakdowns. I am quite sure that in our systems the structural breakdown in the BOM is slightly different than the structure of logistical breakdown. Currently they are handled in different tools, but if we bring them together in SAF we have to find a proper way to do it.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/GfSE/SAF-Specification/issues/17#issuecomment-1750021264
>You are receiving this because you were assigned.
>
>Message ID: ***@***.***>
Do these 'groups' have own specification, Life cycle and so on? Then they might be systems Elements(real systems).

But to me it sounds as if these groups are a entirely different concept than the system-subsystem relationship captured in the structure viewpoint.
More like an integration, or assembly concept.

If that is true, that should be moved to a new VP.
Please think in terms of stakeholders and concerns.

-- 
Gruß,
Alexander

**Comment by haarer** [comment]
I've updated the concerns, descriptions, example and have set the vp to released, since i believe we have the basics covered. 

The concept  "domain" architectures is a bit too unripe to include it for now, IMHO. We should consider this later.
