### ISSUE TITLE
To Complete Viewpoint SPV08a Physical Logical Mapping

### ISSUE THREAD

**Issue by parkaneric** [GfSE/SAF-Specification#18]
Please complete the viewpoint SPV08a Physical Logical Mapping profile to the VP specification.

Assumed priority: medium

Acceptance Criteria:
- viewpoint page (https://github.com/GfSE/SAF-Specification/blob/main/developing-saf/viewpoints/Physical-Logical-Mapping-Viewpoint.md) includes also the profile definition
- maturity is in state released

**Comment by AckvaS** [comment]
- Concept to contain the allocation as the binding element beween logical and physical.
- The profile diagram can be cleaned out to supress elements not relevant to view (i.e. functions) and therefore add the block as the general element for logical/physical elements.

**Comment by haarer** [comment]
concept & profile should be ready, concerns purpose, applicability need more work.
Uses "Allocation of usage" . 
The relationship between definition is derived - to be implemented as a derived property.
(implementation in profile not yet done.)

**Comment by haarer** [comment]
I have released the vp, 
Purpose, applicability, presentation might require some more redactional work.
concern has all rationales,  and is ok, IMO.
