### ISSUE TITLE
To Complete Viewpoint SPV04b  Physical Internal Exchange

### ISSUE THREAD

**Issue by haarer** [GfSE/SAF-Specification#20]
https://github.com/GfSE/SAF-Specification/blob/main/developing-saf/viewpoints/Physical-Internal-Exchange-Viewpoint.md

Assumed priority: medium

- **Review concerns , also remove redundant concerns, and add Rationale to concerns**
- **add example**
- **reference SEHB5**

**Comment by hugoormo** [comment]
- I'd rather use port nesting when modeling interfaces with pin-out description for three reasons:
1 nested ports are normative and thus easier to understand.
2 nested ports reinforce the analogy with the physical port that they are meant to represent. So you see an interaction point as a single physical element.
3 I do not see a dependency between the pin and the TCP/IP signal, but rather an allocation. I see thus the containment relationship in a nested port represent better this situation.
- _"the delegation of SOI element interfaces to SOI boundary interfaces"_ I would rather speak of delegation in terms of **interaction points** <<port>> and not **interfaces** <<interface block>>. We are not actually identifying interfaces but interaction points in this Viewpoint. The interfaces are identified in the "Physical Interface Definition Viewpoint"
- _"states [,] to which other SOI elements the interfaces are connected to"_
- _"assigns interface ~~specifications~~ definitions to ~~interfaces~~ interaction points"_
- _"defines the usage of interfaces, e.g., if only a subset of the interfaces is used"_ How? I would use spezialisation of <<Interface Block>> in the "Physical Interface Definition Viewpoint" for this.
- Concern: _"What ~~are~~ data / information items exchanged?"_
- Concern: _"What ~~are~~ is the ~~protocols~~ description for exchanging items on an interface?"_
- Concern: _"What kind of information is exchanged and processed within the system?"_ The <<item flow>> Elements are neither visible in the Viewpoint nor there is a Viewpoint to describe the interaction elements in SAF.
- Unclear how to model SW-Elements in the Viewpoint. Are they references of the HW-Elements? Do they have their own Interfaces? or use the Interfaces of the HW-Elements?
- Concern: _"Which interface partners does a HW item have?"_ Ports broadcast <<item flow>> Elements to all compatible conected <<port>>. If we need more detail, wether a compatible conected <<port>> a "partner" is or not, we need to extend the profile of SAS to add that semantic. I do not think it is necessary.
- Presentation: I would recommend too, to add a table of allocatin between the <<item flow>> and the corresponding <<object flow>>

**Comment by AckvaS** [comment]
The VP focusses on internal interfaces. The first thing that jumps the eye are the "external" connectors to the diagram frame. For completeness and understandability (and borrowed from SPV01), ok. But can we reformat the view to make clear what is on center stage here?

**Comment by AckvaS** [comment]
same comment as on SPV01b regarding "non-nested" ports.
A bit to laissez-faire for my taste, I would put the physical connector in fron row, with additional information inside.

**Comment by AckvaS** [comment]
Wording: one time system /system element is used another time SOI / SOI element - we should stick with one terminology

**Comment by AckvaS** [comment]
What additional information the system or a system element needs to generate to enable testing?
--> Focus is on interface and (see item flow) what information is transferred and not about functions. Therefore rewording of concern proposed:
What additional information the system or a system element **needs to transmit or received** to enable testing?

**Comment by hugoormo** [comment]
![image](https://github.com/GfSE/SAF-Specification/assets/118672247/1b2670a4-3f81-49a7-8cfa-e5ef71dfab67)
Nesting ports for connector/flow is compulsory in SysML 2.0

**Comment by haarer** [comment]
I've updated the concerns, descriptions, example and have set the vp to released, since i believe we have the basics covered.

Especially the concerns have been reworked, beeing more abstract. 
Anything left should go into a new issue.
