### ISSUE TITLE
Change of Stereotype for SAF_OperationPerformerRole

### ISSUE THREAD

**Issue by MarkusAndres** [GfSE/SAF-Specification#35]
Change of SAF_OperationPerformer into SAF_OperationalContextRole to be conform to the other domains.

**Comment by haarer** [comment]
I believe, SAF_OperationalPerformerRole was meant ..
...at least according to our Discussion in the Bi-weekly call :)

_"Implementation of SAF Concept Operational Context Performer Constituent
Operational Context Performer Constituent: An Operational Context Constituent represents a participant in the Operational Activity executing one or more of its atomic actions interacting with other constituents of the identified Operational Context. Specific characteristics and features or, in case of persons or organizational units, knowledge and skills are assigned to a constituent necessary for the execution of the allocated actions.
"_

**Comment by MarkusAndres** [comment]
Yes, correct. Change shall be _SAF_OperationPerformerRole_ into _SAF_OperationContextRole_
