### ISSUE TITLE
C2_CSTD Common standards definition viewpoint to be completed!

### ISSUE THREAD

**Issue by haarer** [GfSE/SAF-Specification#52]
We have now a [standards definition viewpoint ](https://github.com/GfSE/SAF-Specification/blob/main/viewpoints/Common-Standards-Definition-Viewpoint.md)generated from the model.

A [development view ](https://github.com/GfSE/SAF-Specification/blob/main/developing-saf/viewpoints/Common-Standards-Definition-Viewpoint.md)on the VP is now available 

The VP is based on [michaels proposal](https://github.com/mleute/SAF-Specification-newvps/blob/main/viewpoints/Common-Standards-Definition-Viewpoint.md).

The status is still proposed because some key information is missing:

**Applicability**
_Needs to be specified, reference to SEHB5 if possible._

**Stakeholders**
_The description lists stakeholders, but we need to document the information which stakeholders has which concerns, and why (rationale)_

[Customer](https://github.com/GfSE/SAF-Specification/blob/main/stakeholders.md#Customer)
    [Hardware Developer](https://github.com/GfSE/SAF-Specification/blob/main/stakeholders.md#Hardware-Developer)
    [IV&V Engineer](https://github.com/GfSE/SAF-Specification/blob/main/stakeholders.md#IV&V-Engineer)
    [Mechanic Developer](https://github.com/GfSE/SAF-Specification/blob/main/stakeholders.md#Mechanic-Developer)
    [Regulation Authority](https://github.com/GfSE/SAF-Specification/blob/main/stakeholders.md#Regulation-Authority)
    [Safety Expert](https://github.com/GfSE/SAF-Specification/blob/main/stakeholders.md#Safety-Expert)
    [Security Expert](https://github.com/GfSE/SAF-Specification/blob/main/stakeholders.md#Security-Expert)
    [Software Developer](https://github.com/GfSE/SAF-Specification/blob/main/stakeholders.md#Software-Developer)
    [Supplier](https://github.com/GfSE/SAF-Specification/blob/main/stakeholders.md#Supplier)
    [System Architect](https://github.com/GfSE/SAF-Specification/blob/main/stakeholders.md#System-Architect)
    [Common Concerns](https://github.com/GfSE/SAF-Specification/blob/main/stakeholders.md#Common-Concerns)

The concerns are:
**Concerns**
- [What are the relevant issues or versions of the standards to be used for the development of the system?](https://github.com/GfSE/SAF-Specification/blob/main/concerns.md#_2021x_2_8710274_1700821579663_211989_58619)
-  [What is the complete identification of a standard or a specification?](https://github.com/GfSE/SAF-Specification/blob/main/concerns.md#_2021x_2_8710274_1700821607046_355547_58633)
-    [Which other standards are referenced or referred to by applicable standards?](https://github.com/GfSE/SAF-Specification/blob/main/concerns.md#_2021x_2_8710274_1700821592720_121043_58626)
-    [Which standards and specifications are applicable to the system of interest or its system elements and their interfaces and interactions?](https://github.com/GfSE/SAF-Specification/blob/main/concerns.md#_2021x_2_8710274_1700821558610_489259_58612)

Please contribute to this viewpoint, @GfSE/saf !

**Comment by haarer** [comment]
we need also to add a way to reference the standard by items that shall conform to the standard. I propose a dependency <<SAF_Conforms>>

**Comment by haarer** [comment]
i think that the applicability section should state that the  CSTD supports the 
* technical processes and
* the information management process

**Comment by parkaneric** [comment]
Some feedback regarding attributes of the SAF_Standard stereotype: norm type.
Although they apply to (some) norms only, I see the point in categorizing them (and standards).

_"Diese Normenklassen kommen hauptsächlich aus der Maschinensicherheit, finden aber auch bei Functional Safety Anwendung. Ich habe auf der Seite der EU (zur Maschinenrichtlinie https://eur-lex.europa.eu/legal-content/DE/TXT/?uri=CELEX%3A52016XC0115%2801%29) mal diese Definitionen gefunden:
•	Typ-A-Normen
Typ-A-Normen legen grundlegende Begriffe, Terminologie und Gestaltungsleitsätze fest, die für sämtliche Maschinenkategorien anwendbar sind. Die Anwendung derartiger Normen für sich alleine reicht nicht aus, um die Übereinstimmung mit den einschlägigen grundlegenden Sicherheits- und Gesundheitsschutzanforderungen der Richtlinie zu gewährleisten, obwohl sie einen wichtigen Rahmen für die richtige Anwendung der Maschinenrichtlinie bilden und begründet daher keine umfassende Konformitätsvermutung.
•	Typ-B-Normen
Typ-B-Normen befassen sich mit bestimmten Aspekten der Maschinensicherheit oder bestimmten Arten von Schutzeinrichtungen, die über eine große Bandbreite von Maschinenkategorien verwendet werden können. Die Anwendung der Spezifikationen von Typ-B-Normen begründet eine Konformitätsvermutung mit den hierdurch abgedeckten grundlegenden Anforderungen der Maschinenrichtlinie, wenn aus einer Typ-C-Norm oder der Risikobeurteilung des Herstellers hervorgeht, dass eine durch die Typ-B-Norm festgelegte technische Lösung für die betreffende Kategorie oder für das entsprechende Modell der Maschine angemessen ist. Die Anwendung von Typ-B-Normen, die Spezifikationen für gesondert in Verkehr gebrachte Sicherheitsbauteile enthalten, ergibt eine Konformitätsvermutung für die betreffenden Sicherheitsbauteile hinsichtlich der grundlegenden Sicherheits- und Gesundheitsschutzanforderungen, die durch die Normen abgedeckt werden.
•	Typ-C-Normen
Typ-C-Normen enthalten Spezifikationen für eine bestimmte Maschinenkategorie. Die unterschiedlichen Maschinenarten, die zu der durch eine Typ-C-Norm abgedeckten Kategorie zählen, weisen einen gleichartigen Verwendungszweck auf und sind durch gleichartige Gefährdungen gekennzeichnet. Typ-C-Normen können auf Typ-A- oder Typ-B-Normen verweisen, wobei angegeben wird, welche der Spezifikationen der Typ-A- oder Typ-B-Norm auf die betreffende Maschinenkategorie anwendbar sind. Wenn für einen bestimmten Aspekt der Maschinensicherheit eine Typ-C-Norm von den Spezifikationen einer Typ-A- oder Typ-B-Norm abweicht, haben die Spezifikationen der Typ-C-Norm Vorrang gegenüber den Spezifikationen der Typ-A- oder Typ-B-Norm. Die Anwendung der Spezifikationen einer Typ-C-Norm auf der Grundlage der Risikobeurteilung des Herstellers, ergibt eine Konformitätsvermutung mit den grundlegenden Sicherheits- und Gesundheitsschutzanforderungen der Maschinenrichtlinie, die durch die Norm abgedeckt sind. Bestimmte Typ-C-Normen sind als eine aus mehreren Teilen bestehende Reihe aufgebaut. Teil 1 enthält allgemeine Spezifikationen für eine Maschinenfamilie und andere Teile der Norm enthalten Spezifikationen für bestimmte zu dieser Familie gehörende Maschinenkategorien, durch die die allgemeinen Spezifikationen von Teil 1 ergänzt oder abgewandelt werden. Für Typ-C-Normen, die nach diesem Schema aufgebaut sind, ergibt sich die Konformitätsvermutung mit den grundlegenden Anforderungen der Maschinenrichtlinie aus der Anwendung des allgemeinen Teils 1 der Norm in Verbindung mit dem einschlägigen spezifischen Teil der Norm.

Es gibt dann noch Definitionen, die B-Normen in B1 und B2 unterteilen. Aber das führt hier zu weit, denke ich."_

**Comment by haarer** [comment]
Done, see https://saf.gfse.org/userdoc/Common%20Domain/Common%20Standards%20Definition%20Viewpoint.html
