### ISSUE TITLE
C2_ARAS Argumentation Assurance Viewpoint to be reviewed

### ISSUE THREAD

**Issue by clalitsc** [GfSE/SAF-Specification#56]
https://github.com/GfSE/SAF-Specification/blob/main/developing-saf/viewpoints/Argumentation-Assurance-Viewpoint.md

Review findings by Alexander
* Abstract Concepts like Argument must not be exposed
** Some specialized Concepts (Argument Decomposition, Substitution, etc.) are currently not exposed
* Abstract Concept Claimable_Item is abstract, yes, must not be exposed and not be realized

**Comment by haarer** [comment]
Should i set it really to proposed, is'nt under construction more appropiate?

**Comment by clalitsc** [comment]
Re design

**Comment by clalitsc** [comment]
Life cycle impulse

**Comment by haarer** [comment]
Decision in Workgroup Meeting 2024-06-07: 
- set concept Argument to "not abstract"
- mark specializiations of argument as currently not used (like goal and need) 

Reminder: make issue for other exposed abstract concepts
