### ISSUE TITLE
Github SAF Documentation - page content and hierarchy

### ISSUE THREAD

**Issue by clalitsc** [GfSE/SAF-Specification#66]
Is the user looking for all content on the SAF-Specification start page in the current thematic breadth? Is the information on SAF releases and tool implementations so relevant for the user that it has to be managed in such a representative way on the SAF-Specification start page? Isn't it possible to manage the less important information on Github SAF-specification subpages in a more suitable form? So, balancing depth and breath addressing information needs?
[SAF-Specification GitHub Wegweiser.pptx](https://github.com/user-attachments/files/16921743/SAF-Specification.GitHub.Wegweiser.pptx)

**Comment by haarer** [comment]
Christian, i like the idea in the ppt, looking like documentation building blocks, and possibly a journey thru them. (if i misunderstood, pls clarify)

I also agree to the Idea to rebalance the Documentation. I have an other concern about the documentation - its "look"
We were up to now happy with the plain markdown approach but i believe we can do better.  An Idea could be to change the documentation to a jekyll based generator scheme like oskar has done it for the [cocoml repo](https://github.com/GfSE/CoCoML-Pagesl) which generates to [a nice looking page](https://cocoml.de/) But perhaps that should be separated entirely.

Below i am trying to collect, which reasons to look into the documentation some one might have. If we agee on these,  then we could optimize the documentation building blocks for these "user stories" in a further step.
- Just attempting to get an overview about SAF : "what's that SAF my Collegue mentionend"
  -> the best result would be if the visitor has this overvie and ideally tells others it is interesting and comes back
- Want to try SAF : "what do i need to try SAF and how to should i begin"
  -> best result: visitor is able to quickly download and install one of the implementations, and starts modeling with saf 
- Using SAF, selecting viewpoints: "which viewpoints should i select for a problem at hand"
- Using SAF, working on viewpoints: "how do i use this specific viewpoint"
- Using SAF, wanting help: "who can help me with a question"
- Using SAF, missing a Feature: "how can i propose to have a feature added"
- Wanting to Contribute: "how can i help developint"
- Wanting to extend : "how can i add company or domain specific viewpoints"
- Developing SAF: "how do i work on the SAF specification

This is a bit similar to the Use Cases Idea in the development documentation. But there has not yet been any discussion what to prioritize.

**Comment by clalitsc** [comment]
SAF Specification GitHub Wegweiser Plus Ausgabe 
[SAF Specification GitHub Wegweiser Plus.pptx](https://github.com/user-attachments/files/16923438/SAF.Specification.GitHub.Wegweiser.Plus.pptx)

**Comment by clalitsc** [comment]
FAF Architectures and Architectural Frameworks with MBSE.pdf
[Uploading [Rogers2015] FAF Architectures and Architectural Frameworks with MBSE.pdf…]()

**Comment by haarer** [comment]
Am 8. September 2024 12:07:06 MESZ schrieb Christian Lalitsch-Schneider ***@***.***>:
>Is the user looking for all content on the SAF-Specification start page in the current thematic breadth? Is the information on SAF releases and tool implementations so relevant for the user that it has to be managed in such a representative way on the SAF-Specification start page? Isn't it possible to manage the less important information on Github SAF-specification subpages in a more suitable form? So, balancing depth and breath addressing information needs?
>[SAF-Specification GitHub Wegweiser.pptx](https://github.com/user-attachments/files/16921743/SAF-Specification.GitHub.Wegweiser.pptx)
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/GfSE/SAF-Specification/issues/66
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
Moin, ich habe in der neuen Doku die Navigation ja neu balanciert. 
Was meinst Du, sollte releases und Implementation ein top Level Item sein ?
Wie würdest du die Navigation aufbauen?


-- 
Gruß,
Alexander

**Comment by clalitsc** [comment]
Ich würde unter "Introduction to SAF" eine Übersicht über die Webseiten Inhalte anbieten wollen, eine Informations & Inhalte Landkarte.
[SAF.Specification.GitHub.Wegweiser.Plus2.pptx](https://github.com/user-attachments/files/17002015/SAF.Specification.GitHub.Wegweiser.Plus2.pptx)
