### ISSUE TITLE
Changing the Direction of Refinement 

### ISSUE THREAD

**Issue by MarkusAndres** [GfSE/SAF-Specification#72]
[devdoc/Functional Domain/System Capability Mapping Viewpoint.md](../blob/main/src/devdoc/Functional Domain/System Capability Mapping Viewpoint.md)

Would it make sense to change the direction of the SAF_SystemRequirementRefinement

**Comment by haarer** [comment]
Hi Mark, i dont think it should be changed.
SAF_SystemRequirementRefinement

The system requirement depends on the other Elements and shall be Client in the relationship..

The Relationship ist about the reasoning of system requirements. 
This is an aspect that is typically dropped in nearly every "RFLP" approach i've  seen.

Day zero, a thundering voice :
" there shall be requirements"

😃
