### ISSUE TITLE
D2_COTD Multiplizität Issue

### ISSUE THREAD

**Issue by clalitsc** [GfSE/SAF-Specification#77]
D2_COTD Framework Concept Definition Viewpoint
https://saf.gfse.org/devdoc/SAF%20Development%20Domain/Framework%20Concept%20Definition%20Viewpoint.html
Bitte die Multiplizität des SE Concept Elements abhändern in [1] ... [1..*]. Ein SE Concept Baustein kann mit vielen in Verbindung stehen.

Anlage
![Ontology Definition Process](https://github.com/user-attachments/assets/56057cee-768e-4770-9a52-1d646e013091)

**Comment by haarer** [comment]
Am 3. November 2024 22:31:05 MEZ schrieb Christian Lalitsch-Schneider ***@***.***>:
>D2_COTD Framework Concept Definition Viewpoint
>https://saf.gfse.org/devdoc/SAF%20Development%20Domain/Framework%20Concept%20Definition%20Viewpoint.html
>Bitte die Multiplizität des SE Concept Elements abhändern in [1] ... [1..*]. Ein SE Concept Baustein kann mit vielen in Verbindung stehen.
>
>Anlage
>![Ontology Definition Process](https://github.com/user-attachments/assets/56057cee-768e-4770-9a52-1d646e013091)
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/GfSE/SAF-Specification/issues/77
>You are receiving this because you were assigned.
>
>Message ID: ***@***.***>
Da steht schon * .. *.
Das heißt any .. any 

Ist m.E. eine spitzfindigkeit (bei selbstreferentiellen Relationen) ob man da 1-- 0..* oder 1 - * oder * - * schreibt.

Alles besagt das beliebige Beziehungen existieren können aber nicht müssen.

Und genau das ist gemeint. 
-- 
Gruß,
Alexander

**Comment by haarer** [comment]
Mit ist noch etwas anderes aufgefallen:

Es fehlen folgende Aussagen 
1. Wir können Relationen auf Relationen abbilden

2. Eine spezielle Relation ist die Spezialisierung. 

Diese Möglichkeiten sollte man m.E.  sichtbar machen. Dann kann man sich im Profildiagramm darauf beziehen.

**Comment by clalitsc** [comment]
Ich ziehe die Eindeutigkeit der Lesbarkeit / Definition immer Spitzfindigkeiten wie "any" vor. Rahmenwerk Regeln sind nur auf Basis eindeutiger Definitionen zu definieren. 
Kann es überhaupt den Fall geben, dass SE Concept keine relation zu anderen SE Concepts aufweist? Was wäre ein Beispiel? Ist der Fall sinnvoll und im Rahmen der SE Ontologie Definition beachtenswert?
