### ISSUE TITLE
D2_VPTD Fehlende Relation Issue

### ISSUE THREAD

**Issue by clalitsc** [GfSE/SAF-Specification#78]
D2_VPTD Framework Viewpoint Definition Viewpoint
https://saf.gfse.org/devdoc/SAF%20Development%20Domain/Framework%20Viewpoint%20Definition%20Viewpoint.html
Bitte eine Relation von Viewpoint Baustein auf sich selbst einbringen. Ein Viewpoint Baustein kann mit vielen in Verbindung stehen, Multiplizität [1] ... [1..*].

Anlage
![Viewpoint Definition Process](https://github.com/user-attachments/assets/b2d7cc6a-2fe7-4330-8ea0-37ba45bf48b8)

**Comment by haarer** [comment]
Am 3. November 2024 22:40:23 MEZ schrieb Christian Lalitsch-Schneider ***@***.***>:
>D2_VPTD Framework Viewpoint Definition Viewpoint
>https://saf.gfse.org/devdoc/SAF%20Development%20Domain/Framework%20Viewpoint%20Definition%20Viewpoint.html
>Bitte eine Relation von Viewpoint Baustein auf sich selbst einbringen. Ein Viewpoint Baustein kann mit vielen in Verbindung stehen, Multiplizität [1] ... [1..*].
>
>Anlage
>![Viewpoint Definition Process](https://github.com/user-attachments/assets/b2d7cc6a-2fe7-4330-8ea0-37ba45bf48b8)
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/GfSE/SAF-Specification/issues/78
>You are receiving this because you were assigned.
>
>Message ID: ***@***.***>
Was für eine Bedeutung hat die Beziehung zwischen den Viewpoints? 

-- 
Gruß,
Alexander

**Comment by clalitsc** [comment]
Ich dachte, dass die VP Beschreibungen ein Feld haben, dass sich "related viewpoints" nennt.
![Related Viewpoints](https://github.com/user-attachments/assets/f07ce4be-100c-461d-b348-99736dbdc21a)

**Comment by haarer** [comment]
Am 4. November 2024 12:13:26 MEZ schrieb Christian Lalitsch-Schneider ***@***.***>:
>
>Ich dachte, dass die VP Beschreibungen ein Feld haben, dass sich &quot;related viewpoints&quot; nennt.
>![Related Viewpoints](https://github.com/user-attachments/assets/f07ce4be-100c-461d-b348-99736dbdc21a)
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/GfSE/SAF-Specification/issues/78#issuecomment-2454436266
>You are receiving this because you were assigned.
>
>Message ID: ***@***.***&gt;

Wenn wir das mit in die Konzept Ebene  aufnehmen wollen, sollten dann die Relationen unterschieden werden ?

Das eine ist ja eine  Abhängigkeit wo man Modellelemente aus dem anderen VP braucht. Das andere eine indirekte, wo man als Mensch Inhalte des einen VP anschaut und durch nachdenken andere erarbeitet.

Wobei man in ersten Fall die Elemente manchmal auch im abhängigen VP definieren könnte.

Also wie bei context Definition und use Case. Man kann im Prinzip die Kontext Elemente auch im uc vp anlegen... Wir schreiben aber den ctx def vp als required vor. Ist nicht so ganz konsequent.

Die eine Art related wäre also die Aussage "es sind die selben Konzepte drin" 

Die andere wäre die inhaltliche Abhängigkeit. So wie zwischen operational Performer und Kontext Elementen. 

Ergibt das aus deiner Sicht Sinn ?
-- 
Gruß,
Alexander

**Comment by clalitsc** [comment]
![VP relationships view](https://github.com/user-attachments/assets/11202635-15a1-4db4-82f1-f0633c31c170)
Weder noch. Weder inhaltlich, Nutzung der gleichen Konzepte, noch gedanklich.

**Comment by haarer** [comment]
Am 5. November 2024 21:13:56 MEZ schrieb Christian Lalitsch-Schneider ***@***.***>:
>
>![VP relationships view](https://github.com/user-attachments/assets/11202635-15a1-4db4-82f1-f0633c31c170)
>Weder noch. Weder inhaltlich, Nutzung der gleichen Konzepte, noch gedanklich.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/GfSE/SAF-Specification/issues/78#issuecomment-2458068560
>You are receiving this because you were assigned.
>
>Message ID: ***@***.***&gt;

Ich frage mich nur wer dann die Inhalte für die Relationen bereit stellt.

Wenn man das Konzept einführt dann sollte es ja vermutlich im vptd Exposed werden und in der Doku auftauchen..

-- 
Gruß,
Alexander
