### ISSUE TITLE
D1_STKD + D6_CCND + D6_RATD Don't Repeat Yourself

### ISSUE THREAD

**Issue by clalitsc** [GfSE/SAF-Specification#79]
D1_STKD Framework Stakeholder Definition Viewpoint
D6_CCND Framework Concern Definition Viewpoint
D6_RATD Framework Rationale Definition Viewpoint

Die Inhalte der drei Dev Ops VPs sind deckungsgleich. Bedarf es für 3 Konezptelemete 3 eigenständige Viewpoint Definitionen? Und warum ist D1_STKD unter dem SAF Aspekt "context und exchange" eingeordnet?

**Comment by haarer** [comment]
Am 3. November 2024 22:46:45 MEZ schrieb Christian Lalitsch-Schneider ***@***.***>:
>D1_STKD Framework Stakeholder Definition Viewpoint
>D6_CCND Framework Concern Definition Viewpoint
>D6_RATD Framework Rationale Definition Viewpoint
>
>Die Inhalte der drei Dev Ops VPs sind deckungsgleich. Bedarf es für 3 Konezptelemete 3 eigenständige Viewpoint Definitionen? Und warum ist D1_STKD unter dem SAF Aspekt "context und exchange" eingeordnet?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/GfSE/SAF-Specification/issues/79
>You are receiving this because you were assigned.
>
>Message ID: ***@***.***>
Die Tabellen sind nicht gleich.
Einmal steht der Stakeholder im Fokus und es werden nachrangig die concerns eines Stakeholders mit aufgeführt.
Dann steht die rationale im Vordergrund, nachrangig mit STK und concern. 

Dann concerns min Viewpoints und STK als sekundäre Info.

Du kennst den die Tabellen doch und den Sinn dieser unterschiedlichen sichten. Wie würdest du das machen, alles in einem Viewpoint?
-- 
Gruß,
Alexander

**Comment by clalitsc** [comment]
Definiert jetzt die Art der View, das Layout einer Tabelle mit vor- und nachrangigen Focus, einen Viewpoint? Architecture Viewpoint <<governs>> Architecture View, 1:n? 
Stand heute weisen die 3 VP Definition eine fast vollständige inhaltliche Deckungsgleichheit, siehe Applicability und Presentation, auf. Im Sinne von DRY, KISS, Kohäsion fällt es mir schwer nachzuvollziehen, warum es dreier VP Definitionen bedarf. In der nahen oder fernen Zukunft können sich Dinge möglicherweise anders darstellen.

**Comment by clalitsc** [comment]
Warum D1_STKD + D6_CCND + D6_RATD nicht zusammenfassen und es Viewpoint Needs Viewpoint nennen?

**Comment by haarer** [comment]
Am 4. November 2024 23:13:23 MEZ schrieb Christian Lalitsch-Schneider ***@***.***>:
>
>Warum D1_STKD + D6_CCND + D6_RATD nicht zusammenfassen und es Viewpoint Needs Viewpoint nennen?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/GfSE/SAF-Specification/issues/79#issuecomment-2455807653
>You are receiving this because you were assigned.
>
>Message ID: ***@***.***&gt;

Oh oh.. 
Bloß nicht need ..

Wir verwenden das aus gutem Grund nicht.

Außerdem haben wir schon den Begriff concern.

Man könnte, wenn man einen "Framework Stakeholder and concern VP" macht fragen warum wir das da zusammen fassen und bei den anderen entity stakeholdern und den entsprechenden requirements nicht. 

Symmetrie und so.

Oder man fragt anders Rum warum man bei den entity stakeholdern keine concerns findet und beim Framework doch.
-- 
Gruß,
Alexander

**Comment by clalitsc** [comment]
Framework Stakeholder and Concern Viewpoint, OK für mich
