### ISSUE TITLE
Frage zu den 3 Tool Implementation Repository Seiten

### ISSUE THREAD

**Issue by clalitsc** [GfSE/SAF-Specification#81]
Frage zu den 3 Tool Implementation Repository Seiten
* Folge ich auf den jeweiligen Repository Seiten dem Link „List of Stereotypes“, werde ich auf eine SAF-Seite geführt, die in der Überschrift den Namen „Stereotypes“ trägt. Perfekt. Der Link hält das, was er mir als Leser verspricht.
** https://saf.gfse.org/version/TdSE2024/userdoc/stereotypes.html
* Folge ich dem Link „SAF-Sepcification“, werde ich auf eine SAF-Seite geführt, die in der Überschrift den Namen „Introduction“ trägt. Hält der Link das, was er mit als Leser verspricht? Was ich zu sehen bekommen, ist unser Bild zu UAF, NAF und ADNBw.
** https://saf.gfse.org/version/TdSE2024/

Ist für jemanden, der sich für die „SAF-Specification“ interessiert, die „Introduction“ Seite der richtige Einstieg in SAF? Frage an Euch: Wohin möchtet Ihr den Leser per Link führen? User Docu oder Dev Docu? 
Und die Suche nach „SAF-Specification“ führt im Kontent von sfa.gfse.org zu einem einzigen Suchtreffer: 
** https://saf.gfse.org/version/TdSE2024/userdoc/contributing.html#how-to-contribute-to-saf

![Tool Implementation Repositories](https://github.com/user-attachments/assets/e1a4971a-bbc8-4b6d-86a8-3118f423f338)

Gruss Christian
PS: Viel Spass auf dem TdSE in Leipzig wünsch' ich Euch.

**Comment by haarer** [comment]
Am 9. November 2024 14:08:45 MEZ schrieb Christian Lalitsch-Schneider ***@***.***>:
>Frage zu den 3 Tool Implementation Repository Seiten
>* Folge ich auf den jeweiligen Repository Seiten dem Link „List of Stereotypes“, werde ich auf eine SAF-Seite geführt, die in der Überschrift den Namen „Stereotypes“ trägt. Perfekt. Der Link hält das, was er mir als Leser verspricht.
>** https://saf.gfse.org/version/TdSE2024/userdoc/stereotypes.html
>* Folge ich dem Link „SAF-Sepcification“, werde ich auf eine SAF-Seite geführt, die in der Überschrift den Namen „Introduction“ trägt. Hält der Link das, was er mit als Leser verspricht? Was ich zu sehen bekommen, ist unser Bild zu UAF, NAF und ADNBw.
>** https://saf.gfse.org/version/TdSE2024/
>
>Ist für jemanden, der sich für die „SAF-Specification“ interessiert, die „Introduction“ Seite der richtige Einstieg in SAF? Frage an Euch: Wohin möchtet Ihr den Leser per Link führen? User Docu oder Dev Docu? 
>Und die Suche nach „SAF-Specification“ führt im Kontent von sfa.gfse.org zu einem einzigen Suchtreffer: 
>** https://saf.gfse.org/version/TdSE2024/userdoc/contributing.html#how-to-contribute-to-saf
>![Tool Implementation Repositories](https://github.com/user-attachments/assets/e1a4971a-bbc8-4b6d-86a8-3118f423f338)
>
>Gruss Christian
>PS: Viel Spass auf dem TdSE in Leipzig wünsch' ich Euch.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/GfSE/SAF-Specification/issues/81
>You are receiving this because you were assigned.
>
>Message ID: ***@***.***>
Hi, 
Ich finde es schon richtig die User auf die Hauptseite der Dokumentation zu lenken. Ob der Link dann Specification heißen muss.. kann man in Frage stellen.

Ich habe auch den Gedanken gehabt, das man das GfSE/SAF repo eigentlich nicht mehr braucht und alles was da von wert steht entweder in die Doku Site integrier, oder gleich auf die AG Seite schiebt. 

Auf der AG Seite kann gerne die AG vorgestellt werden, wobei ich Vermeiden würde da Content abzuladen der öfter als 1x in Jahr aktualisiert werden muss.. 
-- 
Gruß,
Alexander

**Comment by clalitsc** [comment]
Ich denke, es sollte eine Seite sein, die das SAF Grid zeigt. Erstaunlich ist, dass egal von wo man aus der Navigationsleiste hin spring, man nie hervorgehoben das SAF Grid sieht - ja es kommt au die Monitorgröße an. Nur 2 mal das UAF Bild. Langsam glaube ich, dass wir das UAF Bild auf dem Produktkarton haben. Und das Bild hat schon Aiste zur einer Fehlinterpretation verführt. Nur der abschließende Gedanke.
Früher ... https://github.com/GfSE/SAF-Specification/blob/legacy-doc/README.md#saf-viewpoint-grid
