### ISSUE TITLE
Change to better readable domain colors

### ISSUE THREAD

**Issue by haarer** [GfSE/SAF-Specification#91]
Some of the grid domain colors are poorly readable, and require changing the font color in grid representing diagrams.
The first row are the current colors.

![grafik](https://github.com/user-attachments/assets/0e60f75b-1bad-4ebd-a9cb-eeb7b15a0a13)

The lower color row comes from the power point standard colors - they should be good on most monitors and beamers.

And they dont require changing the font color.
I propose to change the domain colors as shown.

**Comment by MarkusAndres** [comment]
I woult prefet to to switch the text colour to white for all. The new colours of the elements fit better now than before.

**Comment by haarer** [comment]
Ok, then i'll  document the colors here 
https://saf.gfse.org/devdoc/icons/readme.html
and run an update of the documentation. I'll also update the styles in the example model.

**Comment by haarer** [comment]
Domain Farben->umsetzen. 
    Schriftfarbe ist frei und sollte von der Domainfarbe abweichen und lesbar sein und überhaupt. :) 
    Keine zwingende Verwendung von Icons.
